### ISSUE TITLE
Administrator Access "Corporate Login" lands on "Oops, you've found a dead link."

### ISSUE THREAD

**Issue by ricardoteixeiraduarte** [bitium/jira-saml-plugin#11]
Administrator Access "Corporate Login" lands on "Oops, you've found a dead link."

The URL that is "dead" is:
  https://JIRA_URL/secure/admin/plugins/servlet/saml/auth

**Comment by thnetila** [comment]
I have the same problem.

**Comment by goosetav** [comment]
dup of #7
