### ISSUE TITLE
configure screen missing sidebar

### ISSUE THREAD

**Issue by goosetav** [bitium/jira-saml-plugin#2]
when navigating to the configuration screen, the layout changes 

![image](https://cloud.githubusercontent.com/assets/57294/8448940/a38938b8-1f81-11e5-99ac-510d504fd9cf.png)

![image](https://cloud.githubusercontent.com/assets/57294/8448952/bafa1d64-1f81-11e5-9f76-f66f43b112fe.png)

**Comment by gammalyrae** [comment]
Fixed. Also had to create a link in a sidebar under "Mail". Hipchat also did this, so it's most likely a hack they came up with.
