### ISSUE TITLE
Redirect to called URL

### ISSUE THREAD

**Issue by rkadam** [bitium/jira-saml-plugin#23]
This issue is very similar to issue reported in [Confluence SAML Plugin](https://github.com/bitium/confluence-saml-plugin/issues/35)

Luckily the solution I proposed for Confluence Plugin is applicable here too. I've this successfully working in our DEV environment. Will add more details soon.

**Comment by rkadam** [comment]
I've pushed changes to forked version. Will find out how to send push request so that they are included in main repository here!

**Comment by rkadam** [comment]
Quick updates: While we are waiting for our changes to be merged into main branch here, we went ahead with forked branch (plugin branch) and deployed it into Production.

Users seems to be happy :+1:

Thank you everyone for all your help. Wishing you all a very happy new year!

cheers,
Raju

**Comment by rkarodia** [comment]
Merged into develop. Will be included in the next release soon

**Comment by rkadam** [comment]
Ramone -- Thanks for merging changes to main branch. Hoping we will have updated version released soon.
