### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by puffaz** [bitium/jira-saml-plugin#26]
Hello,

Thanks for the plugin. We were able to configure it, but the button "Use Corporate login" only appears in /login.jsp.

Unfortunately there's no button in dashboard login form /secure/Dashboard.jspa

The same is true for Service Desk Portal /servicedesk/customer/user/login

It would be great to have these missing buttons.

**Comment by orangewolf** [comment]
Thank you for this awesome plugin.  #10  appears to fix the button problem with /secure/Dashboard.jspa, but it does not fix it on the Service Desk.  SSO still does not appear there.
