### ISSUE TITLE
missing corp login button on dashboard

### ISSUE THREAD

**Issue by goosetav** [bitium/jira-saml-plugin#4]
![image](https://cloud.githubusercontent.com/assets/57294/8449051/a5f79260-1f82-11e5-98df-b0889dc06b89.png)

It shows up if you click "Log In" but not on the default dashboard. The button should show in both places.

**Comment by gammalyrae** [comment]
Fixed, It does not align super well though, because this login form is in the iframe and it's against the cross-site scripting prevention rules to modify DOM contents inside iframe.

**Comment by gigiba** [comment]
Hi there,
We are running the plugin v1.0.3 on JIRA 6.3.10 but the button does not come up on the dashboard page.

Please can you confirm if the fix is available for JIRA versions prior than 7?

Thanks in advance.

Regards
Luigi
