### ISSUE TITLE
Compilation failure on SsoLoginServlet.java

### ISSUE THREAD

**Issue by alazar-pinterest** [bitium/jira-saml-plugin#5]
I am getting build failure error on branch https://github.com/alazar-pinterest/jira-saml-plugin/tree/getting_it_to_build

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project SAML2PluginJira: Compilation failure
[ERROR] /Users/alazar/Documents/Scripts/bitium/jira-saml-plugin/src/main/java/com/bitium/jira/servlet/SsoLoginServlet.java:[75,63] <T>getEndpoint(java.util.List<T>,java.lang.String,org.opensaml.ws.transport.InTransport) in org.springframework.security.saml.util.SAMLUtil cannot be applied to (java.util.List<org.opensaml.saml2.metadata.Endpoint>,java.lang.String,java.lang.String)

I get the same error on https://github.com/alazar-pinterest/confluence-saml-plugin/tree/building_the_jar , but on the matching SsoLoginServlet.java:97

**Comment by goosetav** [comment]
@alazar-pinterest I'm going to close this for now -- please reopen if you're still having problems. Also, if its easier, I've uploaded a release of the plugin to https://github.com/bitium/jira-saml-plugin/releases
