### ISSUE TITLE
How can I obtain text form of the X.509 certificate form .cer file to put it into text box in configuration pane?

### ISSUE THREAD

**Issue by HronekJ** [bitium/jira-saml-plugin#53]

**Comment by ymaxwell** [comment]
Looks like you just need to convert .cer to a pfx and then you can open in notepad++ and copy the x.509 text. Openssl is the tool i use often but there are many ways to skin the cat. 
https://search.thawte.com/support/ssl-digital-certificates/index?page=content&actp=CROSSLINK&id=SO26449
http://stackoverflow.com/questions/6307886/how-to-create-pfx-file-from-certificate-and-private-key
