### ISSUE TITLE
page not found after SAML 2.0 authentication

### ISSUE THREAD

**Issue by mb92010** [bitium/jira-saml-plugin#54]
We set up the plugin to authenticate and on initial user login it authenticates, creates the user and lands on the Jira dashboard page. Upon subsequent logins, it authenticates then tries to land on the 'SAML endpoint url' defined in the plugin instead of back to the Jira dashboard url.

**Comment by rkarodia** [comment]
Fixed in v1.0.5 https://marketplace.atlassian.com/plugins/com.bitium.jira.SAML2PluginJira/versions#b100000050
