### ISSUE TITLE
Is it compatible with JIRA 7.6?

### ISSUE THREAD

**Issue by Rafa40** [bitium/jira-saml-plugin#65]
Basen on information in
https://marketplace.atlassian.com/plugins/com.bitium.jira.SAML2PluginJira/server/overview
the plugin is not compatible with JIRA 7.6.x

Is it correct?
Thank you in advance

**Comment by compuguy** [comment]
According to this article @Rafa40 it seems to work with Jira 7.10.1: https://medium.com/@int128/jira-and-confluence-saml-sso-with-keycloak-169c00d43405
