### ISSUE TITLE
Ms ADFS

### ISSUE THREAD

**Issue by ViceIce** [bitium/jira-saml-plugin#8]
I sucessfully configured sso against adfs. Maybe you can add a wiki page for it?

Here are the configuration details:

JIRA:
* Login URL: http://[ADFS-SERVER]/adfs/ls
* Entity ID: http://[ADFS-SERVER]/adfs/services/trust

ADFS:
* Relaying Party Identifier: https://[JIRA-SERVER]:443/confluenceSAML
* Relaying Party Endpoint (POST): https://[JIRA-SERVER]/plugins/servlet/saml/auth
* Send SAM-Account-Name as Name ID Claims

Regards,
Michael

**Comment by goosetav** [comment]
hi Michael, the wiki should be writeable by anyone -- feel free to add a page with information on configuring ADFS

**Comment by ViceIce** [comment]
Ok. Thanks.
