### ISSUE TITLE
Windows Active Directory 

### ISSUE THREAD

**Issue by jirauser2015** [bitium/jira-saml-plugin#9]
We are using Microsoft Active Directory, can we use this plugin to enable single sign on with AD? Please let me know if more details are required.

**Comment by goosetav** [comment]
a user contributed a wiki article on the settings for ADFS https://github.com/bitium/jira-saml-plugin/wiki/ADFS

**Comment by jirauser2015** [comment]
Relaying Party Identifier: https://[JIRA-SERVER]:443/confluenceSAML
JIRA is hosted behind firewall and https is not enabled. Is there any limitation for http?

**Comment by goosetav** [comment]
I haven't tested it with only http -- in theory it should work

**Comment by crk26** [comment]
ADFS won't work with http. https is mandatory.
